# Generated by Django 3.1.4 on 2021-11-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Працягласць віктарыны ў хвілінах')),
                ('required_score_to_pass', models.IntegerField(help_text='патрабаваны бал у %')),
                ('difficluty', models.CharField(choices=[('лёгка', 'лёгка'), ('сярэдняя ', 'сярэдняя '), ('цяжка ', 'цяжка')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Вiктарыны',
            },
        ),
    ]
